import { BaseService } from './BaseService';

interface ScoringFactors {
    interestAlignment: number;  // 1-100
    skillCompatibility: number; // 1-100
    personalityMatch: number;   // 1-100
    growthPotential: number;    // 1-100
    lifestyleAlignment: number; // 1-100
    exposurePerformance: number;// 1-100
}

export class ScoringEngine extends BaseService {

    // Customizable weights. Future enhancement: pull from DB configuration
    private weights = {
        interestAlignment: 0.25,
        skillCompatibility: 0.20,
        personalityMatch: 0.15,
        growthPotential: 0.15,
        lifestyleAlignment: 0.10,
        exposurePerformance: 0.15
    };

    /**
     * Recalculates the overall match score for a career option based on newly submitted data.
     */
    async recalculateCareerScore(careerOptionId: string, factors: ScoringFactors) {
        let finalScore = 0;

        finalScore += factors.interestAlignment * this.weights.interestAlignment;
        finalScore += factors.skillCompatibility * this.weights.skillCompatibility;
        finalScore += factors.personalityMatch * this.weights.personalityMatch;
        finalScore += factors.growthPotential * this.weights.growthPotential;
        finalScore += factors.lifestyleAlignment * this.weights.lifestyleAlignment;
        finalScore += factors.exposurePerformance * this.weights.exposurePerformance;

        const roundedScore = Math.round(finalScore);

        return await this.db.careerOption.update({
            where: { id: careerOptionId },
            data: { match: roundedScore }
        });
    }

    /**
     * Allows the system to do a side-by-side comparison of the top 2 shortlisted careers.
     */
    async generateComparison(reportId: string) {
        const shortlistedOptions = await this.db.careerOption.findMany({
            where: { reportId, isShortlisted: true },
            take: 2,
            include: { research: true, skillGaps: true }
        });

        if (shortlistedOptions.length < 2) {
            throw new Error("Need exactly 2 shortlisted careers for a final comparison.");
        }

        // Example structuring logic for comparison
        const comparisonData = {
            option1: shortlistedOptions[0].title,
            option2: shortlistedOptions[1].title,
            scoreDiff: Math.abs(shortlistedOptions[0].match - shortlistedOptions[1].match),
            // In reality, an AI service layer would enrich this
            aiReasoning: "Generated by AIService"
        };

        return await this.db.finalPlan.upsert({
            where: { reportId },
            update: { comparisonData },
            create: { reportId, comparisonData } // finalRoadmap added later
        });
    }
}

export const scoringEngine = new ScoringEngine();
